# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{presentable}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["toastyapps"]
  s.date = %q{2009-12-17}
  s.description = %q{Making presenters easy and fun!}
  s.email = %q{matt@toastyapps.com}
  s.files = [
    ".gitignore",
     "Rakefile",
     "Readme.textile",
     "VERSION",
     "lib/presentable.rb",
     "lib/presenter.rb",
     "presentable.gemspec",
     "rails/init.rb",
     "test/presenter_test.rb",
     "test/presenters/post_presenter.rb",
     "test/presenters/post_rss_presenter.rb",
     "test/presenters/rss_presenter.rb",
     "test/schema.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/toastyapps/presentable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Making presenters easy and fun!}
  s.test_files = [
    "test/presenter_test.rb",
     "test/presenters/post_presenter.rb",
     "test/presenters/post_rss_presenter.rb",
     "test/presenters/rss_presenter.rb",
     "test/schema.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

